# Detta är en template för en docker compose.
# Syftet är att se alla möjliga tänkbara keys.
# En hemsida med massa samples för att lära sig : https://github.com/docker/awesome-compose
services: 
  html:
    build:
      dockerfile: Dockerfile
    ports: 
      - "521:80" # DEn till höger Värdporten är och den till vänster är kontainerportden
  html2: 
    build: 
      dockerfile: dolche
